### ISSUE TITLE
Missing BtwSoort::VERLEGD()

### ISSUE THREAD

**Issue by nro-bowa** [iwd-nl/snelstart-php#24]
Recently I've started to integrate your library for a customer but I've noticed that on the [BtwSoort](https://github.com/iwd-nl/snelstart-php/blob/6b2b1261df5a5a8e71d7e513d490e391fff4dc03/src/Model/Type/BtwSoort.php) class, the VERLEGD property is missing. 
Most probably this is intended, but I don't understand why the "[BtwRegelSoort](https://github.com/iwd-nl/snelstart-php/blob/3b7dc5baf3ba61c1fb77b2b6b85510c603eb43d1/src/Model/Type/BtwRegelSoort.php)" has more properties and "[BtwSoort](https://github.com/iwd-nl/snelstart-php/blob/6b2b1261df5a5a8e71d7e513d490e391fff4dc03/src/Model/Type/BtwSoort.php)" doesn't.

Can you provide us with more insights on how we should use your library to specify the content of an invoice that has 2 VATs (eg. LAAG and VERLEGD)? 

Thank you for your time

**Comment by arwinvdv** [comment]
I should think you can't create an invoice with a line vat VERLEGD and another line with a vatrate, because vat VERLEGD is for the whole invoice.
[See belastingdienst.nl](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/btw_berekenen_aan_uw_klanten/waarover_btw_berekenen/verleggingsregeling/hoe_werkt_btw_verleggen)

So you can set `BtwRegelSoort::VERKOPENVERLEGD()` on your invoicelines and `BtwSoort::OVERIG()` on your invoice.
